# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160816090241 on 2016-12-22 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=512)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
