# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160816090241 on 2016-12-22 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplecms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='', max_length=512, verbose_name='\u56fe\u7247\u7684\u5730\u5740'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='uploadImages', verbose_name='\u4e0a\u4f20\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='\u6807\u9898'),
        ),
    ]
