# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160816090241 on 2016-12-22 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplecms', '0002_auto_20161222_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='online_image_url',
        ),
    ]
